### ISSUE TITLE
Missing template when running `npm run build`

### ISSUE THREAD

**Issue by DevLab2425** [thescientist13/greenwood-getting-started#8]
Getting the following error 

```
Error: ENOENT: no such file or directory, mkdir '/path/to/project/greenwood-getting-started/.greenwood/blog/first-post'
```

Full error output

```bash
$ npm run build

> greenwood-getting-started@1.0.0 build /path/to/project/greenwood-getting-started
> greenwood build

-------------------------------------------------------
Welcome to Greenwood ♻️
-------------------------------------------------------
Reading project config
Initializing project workspace contexts
Generating graph of workspace files...
Scaffolding out project files...
Generate pages from templates...
Error: ENOENT: no such file or directory, mkdir '/path/to/project/greenwood-getting-started/.greenwood/blog/first-post'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! greenwood-getting-started@1.0.0 build: `greenwood build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the greenwood-getting-started@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /path/to/log/.npm/_logs/2019-10-03T01_12_47_261Z-debug.log
```

**Comment by thescientist13** [comment]
Interesting @DevLab2425 

Could you share what your directory structure looks like locally for the _src/_ driectory?

**Comment by DevLab2425** [comment]
This was immediately after a clone and a `npm install`.

Here's the `/src` directory

![Screen Shot 2019-10-03 at 8 55 19 PM](https://user-images.githubusercontent.com/8385375/66173842-47d51680-e620-11e9-9c4a-b22adb049aa3.png)

**Comment by hutchgrant** [comment]
```bash
git clone https://github.com/thescientist13/greenwood-getting-started.git
cd ./greenwood-getting-started
yarn install
yarn serve
```
No issues.

**Comment by thescientist13** [comment]
Thanks @DevLab2425 

Going to link it to this issue we've been tracking on our end recently.  Not sure if it's related but kind of hoping it is in the sense of making sure we are able to harden the tool.
https://github.com/ProjectEvergreen/greenwood/pull/217

If you can provide those follow up specs that @hutchgrant requested, that would be helpful too.

Thanks!

**Comment by thescientist13** [comment]
@DevLab2425 
Guessing since that you were able to open the PR for the sticky footer, the `build` command eventually succeeded for you after another try?

**Comment by DevLab2425** [comment]
@hutchgrant
The details....

```
OS: MacOS 10.12.6
node: 12.11.1
npm: 6.11.3
```

As for the `build` command @thescientist13, I took `.greenwood/index/index.js` and duplicated it into `.greenwood/blog/first-post`, and changed the export name. Re-ran the build and it worked.

**Comment by thescientist13** [comment]
interesting, and thanks for providing that info @DevLab2425 . 

Some follow ups
1. So does this error occur for you every time then?  (not intermittent?) 
1. Are you able to try using current LTS Node v10 by chance and see if that helps?

Thanks for the help and appreciate any / all debugging you are able to provide 🙏

**Comment by DevLab2425** [comment]
@thescientist13 @hutchgrant 
When I switch to LTS Node v10.16.3, I have no issue installing and building. However, when switching back to 12.11.1, I can also build successfully. I've tried this multiple times with new clones every time and each time a success. Strange for sure.

**Comment by thescientist13** [comment]
Yeah, sounds like it could be related to this issue we've been tracking
https://github.com/ProjectEvergreen/greenwood/pull/217

We have a PR open for it that I am about review now that @hutchgrant has put a good amount of time into and that we feel will handle all these various inconsistencies we've been observing.  Will then merge  that into our upcoming [0.4.0 release branch PR](https://github.com/ProjectEvergreen/greenwood/pull/188) and then publish a new alpha release.  I will then update [this PR](https://github.com/thescientist13/greenwood-getting-started/pull/7) in the getting started repo here with that new alpha version.  

Maybe you would be up for helping us test that?  (would just be checking out that branch, doing a `yarn install`, and then just playing around with the commands for a bit)

Also, thanks again for trying things out and reporting your feedback!  🙌

**Comment by thescientist13** [comment]
@DevLab2425 
Without going into all the gritty details (although happy to if you're interested), we have released a new alpha version of our upcoming release (0.4.0) which includes what we believe is a fix for this issue.  Would be up for helping us test it out?

You can check out the branch from this PR which has the latest version and try running some of the same commands you did and see if it helps?
https://github.com/thescientist13/greenwood-getting-started/pull/7

Also, you can join us in channel #greenwood on Slack if you have any questions or want to send us some direct feedback.  

Thanks and let us know if you have any questions!  🙌

**Comment by thescientist13** [comment]
`0.4.0` release is out and has been updated in master.  I think this will fix your issue now @DevLab2425 !  Please reopen if you are experiencing any issues!
